all:
	make -f SP13/COGS1/Makefile
	make -f SP13/CSE110/Makefile
	make -f SP13/CSE101/Makefile
	make -f SP13/CSE105/Makefile

clean:
	make -f SP13/COGS1/Makefile clean
	make -f SP13/CSE110/Makefile clean
	make -f SP13/CSE101/Makefile clean
	make -f SP13/CSE105/Makefile clean
