all:
	make -f COGS1/Makefile
	make -f CSE110/Makefile
	make -f CSE101/Makefile
	make -f CSE105/Makefile

clean:
	make -f COGS1/Makefile clean
	make -f CSE110/Makefile clean
	make -f CSE101/Makefile clean
	make -f CSE105/Makefile clean
